Repository gab-cat/merchtrack, pull requests merged in 2025-01, with the labels that each got.

#2 Workflows for CI/CD
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/refactor_suggestion.md
  .github/ISSUE_TEMPLATE/security_vulnerability.md
  .github/dependabot.yml
  .github/workflows/cache.yml
  .github/workflows/production.yml
  .github/workflows/pull-request.yml
  .github/workflows/staging.yml
  Dockerfile
  package.json
  prisma/migrations/20250102062425_init/migration.sql
  prisma/migrations/migration_lock.toml
Labels: enhancement

#14 Add environment file creation in CI workflows
  .github/workflows/production.yml
  .github/workflows/pull-request.yml
  .github/workflows/staging.yml
Labels: bug, enhancement, docker

#15 Env fixes in workflow
  .github/workflows/staging.yml
  Dockerfile
Labels: bug

#23 Datadog integration
  package.json
  pnpm-lock.yaml
  sentry.client.config.ts
  sentry.edge.config.ts
  sentry.server.config.ts
  src/app/global-error.tsx
  src/app/globals.css
  src/app/layout.tsx
  src/components/misc/datadog-init.tsx
  src/config/index.ts
  src/config/monitoring.ts
  src/constants/index.ts
Labels: enhancement, docker

#25 Dockerfile and Workflow Updates
  .github/workflows/staging.yml
  Dockerfile
  src/config/index.ts
  src/config/monitoring.ts
Labels: enhancement, docker, review

#27 Datadog config fixes
  src/components/misc/datadog-init.tsx
  src/config/index.ts
  src/config/monitoring.ts
Labels: review

#29 feat(header): add header component
  public/img/android-chrome-192x192.png
  public/img/android-chrome-512x512.png
  public/img/apple-touch-icon.png
  public/img/favicon-16x16.png
  public/img/favicon-32x32.png
  public/img/merch-track-logo.png
  src/app/layout.tsx
  src/app/page.tsx
  src/components/ui/header.tsx
  src/middleware.ts
Labels: enhancement, review

#32 Devcontainer reconfigure
  .devcontainer/devcontainer.json
  README.md
  static-analysis.datadog.yml
Labels: enhancement, docker, review

#44 Database schema design and workflow implementation
  .github/workflows/migrate.yml
  prisma/migrations/20250113142823_full_fb_init/migration.sql
  prisma/schema.prisma
  src/types/Category.d.ts
  src/types/CustomerSatisfactionSurvey.d.ts
  src/types/CustomerSatisfactionSurveyCategory.d.ts
  src/types/Fulfillment.d.ts
  src/types/Log.d.ts
  src/types/Order.d.ts
  src/types/OrderItem.d.ts
  src/types/Payment.d.ts
  src/types/Product.d.ts
  src/types/User.d.ts
  src/types/index.d.ts
  src/types/index.ts
Labels: bug, enhancement, docker, review, P0 - Critical, backend

#46 Add Cloudflare Web Analytics integration and update layout
  .vscode/settings.json
  src/app/layout.tsx
  src/components/misc/scripts.tsx
  src/config/index.ts
  src/config/monitoring.ts
Labels: enhancement, docker, review

#49 Fix Cloudflare RUM loading
  src/app/layout.tsx
  src/components/misc/datadog-init.tsx
  src/components/misc/scripts.tsx
Labels: bug, enhancement, security, review, P2 - Medium

#50 Client-side Sentry bugfix
  .github/workflows/staging.yml
  next.config.ts
  package.json
  pnpm-lock.yaml
  sentry.client.config.ts
  src/app/global-error.tsx
  src/app/test/page.tsx
  src/components/misc/datadog-init.tsx
  src/middleware.ts
  static-analysis.datadog.yml
Labels: bug, enhancement, dependencies, security, review, P2 - Medium

#58 Further fix and enhancements on #56
  package.json
  pnpm-lock.yaml
  public/img/Footer-BG.png
  public/img/logo-white.png
  src/app/layout.tsx
  src/components/ui/footer.tsx
  src/constants/SEO.ts
  src/constants/footer.ts
  src/constants/index.ts
  src/instrumentation.ts
  src/types/Misc.d.ts
Labels: enhancement, dependencies, review, ui/ux, P1 - High

#60 Project structures and UI improvements
  .vscode/settings.json
  eslint.config.js
  eslint.config.mjs
  next.config.ts
  package.json
  pnpm-lock.yaml
  src/app/(protected)/dashboard/page.tsx
  src/app/(public)/about/page.tsx
  src/app/(public)/contact/page.tsx
  src/app/(public)/faqs/page.tsx
  src/app/(public)/layout.tsx
  src/app/global-error.tsx
  src/app/layout.tsx
  src/app/not-found.tsx
  src/app/page.tsx
  src/components/misc/datadog-init.tsx
  src/components/misc/scripts.tsx
  src/components/public/footer.tsx
  src/components/public/header-links.tsx
  src/components/public/header.tsx
  src/components/ui/button.tsx
  src/components/ui/header.tsx
  src/components/ui/input.tsx
  src/constants/footer.ts
  src/constants/header.ts
  src/constants/index.ts
  src/lib/db.ts
  src/middleware.ts
  src/types/Product.d.ts
Labels: enhancement, dependencies, review, ui/ux, P1 - High

#64 feat(faqs-page): rendering faqs page
  package.json
  pnpm-lock.yaml
  src/app/(public)/faqs/page.tsx
  src/app/(public)/layout.tsx
  src/components/public/faqs-body.tsx
  src/components/public/header.tsx
  src/components/ui/accordion.tsx
  src/components/ui/button.tsx
  src/constants/faqs.ts
  src/constants/index.ts
  tailwind.config.ts
Labels: enhancement, dependencies, review, ui/ux, P1 - High

#65 Feat/database optimizations
  prisma/migrations/20250117175326_db_optimizations/migration.sql
  prisma/migrations/20250120012844_add_message_schema/migration.sql
  prisma/migrations/20250120020136_db_fixes_2/migration.sql
  prisma/schema.prisma
  prisma/schema/category.prisma
  prisma/schema/fulfillment.prisma
  prisma/schema/log.prisma
  prisma/schema/main.prisma
  prisma/schema/message.prisma
  prisma/schema/order.prisma
  prisma/schema/payment.prisma
  prisma/schema/permission.prisma
  prisma/schema/product.prisma
  prisma/schema/survey.prisma
  prisma/schema/user.prisma
  src/components/public/header.tsx
  src/constants/animations.ts
  src/types/Category.d.ts
  src/types/CustomerSatisfactionSurvey.d.ts
  src/types/CustomerSatisfactionSurveyCategory.d.ts
  src/types/Fulfillment.d.ts
  src/types/Log.d.ts
  src/types/Misc.d.ts
  src/types/Order.d.ts
  src/types/OrderItem.d.ts
  src/types/Payment.d.ts
  src/types/Product.d.ts
  src/types/User.d.ts
  src/types/index.d.ts
Labels: bug, enhancement, dependencies, review, P1 - High, P0 - Critical, backend

#63 feat(admin): create admin-orders components
  eslint.config.js
  example.env
  package.json
  pnpm-lock.yaml
  public/img/logo.png
  public/img/sample_pfp.jpg
  src/app/admin/layout.tsx
  src/app/admin/orders/page.tsx
  src/app/page.tsx
  src/components/private/admin-sidebar.tsx
  src/components/private/admin-topbar.tsx
  src/components/private/orders-table.tsx
  src/components/private/page-title.tsx
  src/components/private/status-dropdown.tsx
  src/components/ui/avatar.tsx
  src/components/ui/badge.tsx
  src/components/ui/breadcrumb.tsx
  src/components/ui/button.tsx
  src/components/ui/checkbox.tsx
  src/components/ui/custom-breadcrumbs.tsx
  src/components/ui/dropdown-menu.tsx
  src/components/ui/input.tsx
  src/components/ui/scroll-area.tsx
  src/components/ui/table.tsx
  src/components/ui/tabs.tsx
  src/constants/admin-navigation.ts
  src/constants/index.ts
  src/constants/status-options.ts
  src/middleware.ts
  src/types/Misc.ts
  src/types/index.d.ts
  tailwind.config.ts
Labels: enhancement, dependencies, review, ui/ux, P1 - High, backend

#71 Added paymentSite in db and pages animations
  package.json
  pnpm-lock.yaml
  prisma/migrations/20250120040624_add_payment_site_option/migration.sql
  prisma/schema/payment.prisma
  src/app/(public)/contact/page.tsx
  src/app/(public)/faqs/page.tsx
  src/app/admin/orders/page.tsx
  src/app/admin/payments/page.tsx
  src/components/private/admin-sidebar.tsx
  src/components/private/orders-table.tsx
  src/components/public/header.tsx
  src/components/public/page-animation.tsx
  src/components/public/page-title.tsx
  src/components/ui/dialog.tsx
  src/middleware.ts
  tailwind.config.ts
Labels: enhancement, dependencies, review, ui/ux, P1 - High, backend

#79 feat(contact-db-integration): add db integration
  next.config.ts
  package.json
  pnpm-lock.yaml
  src/actions/public.actions.ts
  src/app/(public)/contact/(components)/contact-form.tsx
  src/app/(public)/contact/page.tsx
  src/app/layout.tsx
  src/app/onboarding/page.tsx
  src/components/private/orders-table.tsx
  src/components/ui/form.tsx
  src/components/ui/input.tsx
  src/components/ui/label.tsx
  src/components/ui/toast.tsx
  src/components/ui/toaster.tsx
  src/hooks/use-toast.ts
  src/lib/db.ts
  src/schema/public-contact.ts
  src/types/index.d.ts
Labels: enhancement, dependencies, review, ui/ux, P1 - High, backend

#107 Imlement Mailgun, Integrate Redis and Messaging system
  next.config.ts
  package.json
  pnpm-lock.yaml
  prisma/migrations/20250128180633_add_replies_to_column/migration.sql
  prisma/migrations/20250129072607_add_image_url/migration.sql
  prisma/schema/message.prisma
  prisma/schema/user.prisma
  public/img/logo.svg
  src/actions/orders.actions.ts
  src/actions/public.actions.ts
  src/actions/users.action.ts
  src/app/(public)/contact/(components)/contact-form.tsx
  src/app/admin/layout.tsx
  src/app/admin/messages/(components)/compose-email.tsx
  src/app/admin/messages/(components)/email-template.tsx
  src/app/admin/messages/(components)/msg-container.tsx
  src/app/admin/messages/(components)/msg-detail-header-content.tsx
  src/app/admin/messages/(components)/msg-detail-original.tsx
  src/app/admin/messages/(components)/msg-detail-reply.tsx
  src/app/admin/messages/(components)/msg-detail-replyform.tsx
  src/app/admin/messages/(components)/msg-detail.tsx
  src/app/admin/messages/(components)/msg-list.tsx
  src/app/admin/messages/(components)/msg-original-skeleton.tsx
  src/app/admin/messages/(components)/msg-skeleton.tsx
  src/app/admin/messages/(components)/msg-tabs.tsx
  src/app/admin/messages/(components)/sent-msg-list.tsx
  src/app/admin/messages/_actions.ts
  src/app/admin/messages/page.tsx
  src/app/admin/orders/page.tsx
  src/app/admin/page.tsx
  src/app/onboarding/_actions.ts
  src/app/page.tsx
  src/components/misc/providers.tsx
  src/components/private/admin-sidebar.tsx
  src/components/private/orders-table-skeleton.tsx
  src/components/public/landing/call-to-action.tsx
  src/components/public/landing/categories-section.tsx
  src/components/public/landing/featured-products.tsx
  src/components/public/landing/hero-section.tsx
  src/components/public/landing/testimonial-section.tsx
  src/components/public/landing/university-merch-section.tsx
  src/components/public/page-animation.tsx
  src/components/ui/alert-dialog.tsx
  src/components/ui/switch.tsx
  src/components/ui/textarea.tsx
  src/components/ui/toaster.tsx
  src/constants/email.ts
  src/constants/index.ts
  src/lib/mailgun.ts
  src/lib/redis.ts
  src/middleware.ts
  src/schema/messages.ts
  src/schema/user.ts
  src/types/messages.ts
  src/utils/permissions.ts
  tailwind.config.ts
Labels: enhancement, dependencies, review, ui/ux, P1 - High, backend

#117 fix: add Clerk secret key to staging workflow
  .github/workflows/staging.yml
Labels: P0 - Critical
