Repository gab-cat/merchtrack, pull requests merged in 2025-02, with the labels that each got.

#120 Integrate custom hooks for actions
  src/actions/messages.actions.ts
  src/actions/orders.actions.ts
  src/app/admin/messages/(components)/email-template.tsx
  src/app/admin/messages/(components)/msg-container.tsx
  src/app/admin/messages/(components)/msg-detail-original.tsx
  src/app/admin/messages/(components)/msg-detail-reply.tsx
  src/app/admin/messages/(components)/msg-detail.tsx
  src/app/admin/messages/_actions.ts
  src/app/admin/messages/page.tsx
  src/components/private/orders-table.tsx
  src/constants/email.ts
  src/hooks/messages.hooks.ts
  src/hooks/orders.hooks.ts
  src/lib/redis.ts
  src/middleware.ts
  src/types/global.d.ts
  src/utils/permissions.ts
Labels: bug, enhancement, dependencies, review, ui/ux, P1 - High, backend

#118 fix(payments): added additional information, fixed specific functiona…
  src/app/admin/payments/page.tsx
  src/components/private/offsite-payment.tsx
  src/components/private/onsite-payment.tsx
  src/components/private/payment-form.tsx
  src/components/private/transaction-history.tsx
  src/components/ui/select.tsx
  src/types/payments.ts
Labels: bug, enhancement, review, ui/ux, P1 - High, backend

#132 Add SEO attributes
  public/site.webmanifest
  src/actions/public.actions.ts
  src/app/layout.tsx
  src/app/robots.ts
  src/app/sitemap.ts
  src/constants/SEO.ts
Labels: enhancement, dependencies, review, ui/ux, P1 - High
